.PHONY:

PAIR=BTC_USDT
STG=inspector
KLINE=bitopro,mock
KLINE_DURATION=1m
TRADE=mock
BT=true
BT_START=2020-01-01
BT_END=2023-12-31

run:
	PAIR=${PAIR} \
	STG=${STG} \
	KLINE=${KLINE} \
	KLINE_DURATION=${KLINE_DURATION} \
	TRADE=${TRADE} \
	BT=${BT} \
	BT_START=${BT_START} \
	BT_END=${BT_END} \
	go run ${CURDIR}/main.go