.PHONY:

PAIR=BTC_USDT
STG=inspector
KLINE=bitopro,mock
KLINE_DURATION=1m
TRADE=mock
BACK_TESTING=true

run:
	PAIR=${PAIR} \
	STG=${STG} \
	KLINE=${KLINE} \
	KLINE_DURATION=${KLINE_DURATION} \
	TRADE=${TRADE} \
	BACK_TESTING=${BACK_TESTING} \
	go run ${CURDIR}/main.go